default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :deploy do
    capture_screenshots
    build_app(scheme: "PdParty")
    upload_to_testflight
  end

  desc "Capture screenshots"
  lane :screenshots do
    capture_screenshots
  end
end
